### ISSUE TITLE
I get this error on running ../configure --with-apps=kmeans then I make k means and I get this next error:

### ISSUE THREAD

**Issue by DAOUDISARA2** [vtsynergy/OpenDwarfs#13]

**Comment by DAOUDISARA2** [comment]
I get this error on running ../configure --with-apps=kmeans
then I make k means
and I get this next error:
![opendrawfs](https://user-images.githubusercontent.com/37963683/52167463-a8235980-271b-11e9-91d2-a7dbed509727.png)

**Comment by zjing14** [comment]
@DAOUDISARA2 I tried to compile the kmeans app on my CUDA machine. I got no issue. Could post your software and hardware environment, and logs of ../configure.

**Comment by DAOUDISARA2** [comment]
note: I did the test with pc i7-3777 CPU @ 3.40ghz and GPU AMD Tahiti OpenclCL 1.1
suave with i3 with integrated graphics and the error remains the same
![drowfs1](https://user-images.githubusercontent.com/37963683/52174861-9765f880-279a-11e9-83cd-df18904253bb.png)
![drowfs2](https://user-images.githubusercontent.com/37963683/52174862-9765f880-279a-11e9-8bbb-6864924e2a3b.png)
![Uploading drowfs3.png…]()

**Comment by DAOUDISARA2** [comment]
![drowfs3](https://user-images.githubusercontent.com/37963683/52174876-cc724b00-279a-11e9-9cc6-cccb8c91ae52.png)

**Comment by psath** [comment]
I have compiled the unmodifed code using the CUDA stack, the AMD APP SDK (deprecated) stack, and the AMD ROCM stack. From your previous post hijacking it is clear that you have modified the code, yet you provide no link to a complete repository to debug the modifications causing the issue (which it is in no way our responsibility to support your modifications, though the above is a simple link error). Further, after being warned not to hijack others' issues, you have persisted in doing so. This issue is locked and you have been suspended from further posts.
