### ISSUE TITLE
Is there a mapreduce benchmark?

### ISSUE THREAD

**Issue by kannaiah** [vtsynergy/OpenDwarfs#9]
There is a file _test/mapreduce/fsa-blastcl/test.fasta_ 
Is there a benchmark that uses this file?

**Comment by jlgreathouse** [comment]
If you're looking for some map reduce benchmarks, this lab just uploaded their StreamMR system: https://github.com/vtsynergy/StreamMR

**Comment by DAOUDISARA2** [comment]
for benchmarking OpenDwarfs  , I tried to execute k-means algorithm, but unfortunately, I have problems whatever one could help me, please

**Comment by zjing14** [comment]
@DAOUDISARA2 Could you create a new issue and post your problems/logs?

**Comment by DAOUDISARA2** [comment]
I have a problem during benchmark execution (K-MEANS OpenCL)
here is the problem :
![capture du 2019-01-31 10-01-51](https://user-images.githubusercontent.com/37963683/52040331-5f12b000-2537-11e9-91c4-19351f97c187.png)

**Comment by psath** [comment]
Off topic with OP. If you have an issue with the code as published, open a new issue, do not necro-post on an unrelated topic.

FWIW your issue is that you have changed the code of kmeans_clustering.c as the reference to kmeansCuda (as published here) should have a capital C, not lowercase.

Topic locked.

**Comment by psath** [comment]
Off-topic, start a new thread if you are having issues compiling _unmodified_ code. Continued off-topic requests to provide support for modifications you have made will be treated as spam.
